# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fiYPupQxGCjnTcajvPGMElsOv8p1Ke/gbovkUPC6XVVrdJuZhTcefVfqEBnzBzb7L9doQ9rkXCNWOZaOKdV1qo5h+hqxr804fPydCSUDnGNpSoEsOfXTwZnal7xgenJAvqnPk0CWP91HqJQVnDkCJoaRZo0+RxdBddPJHFoVQpLKtuOWT3KrQsv4NMu2JGXmG9J05fjYXLgIAFblv7x8ddIAqLhivFa/f2OIxH3y76+emQVIx6qSqVeBGwMT7OFMVBSmvk5CE2JhaLriFwxbRc7/FIF34QPtRB4paoVOx3KYE3aL2evAB+6yX3cMx8sSrkpO0dsGs/B5BRgYyS/tHvQzjl4hV8Y8soLrxKAcENes+10duBDWACohcZYg4d7gFvva73xqGDgrz5z5a7LJBFfOOesMx9/XNiEq8rLZnfzkFtTEmYryC2DjkW7jdCm+44d8Uhr/Yn7DLeZomnaFc4sEr6XfCXzeg56EWTzwzL4sLhUFJyGKrBlxm/on0I7sxoDvSRSOZt3z0T7x3HMzDMVgpTlPItgbr0IDEtxJL9qEX+pdhOS9EvIHlZTUGarClFj1Y/8jdBrD+ZruVbYkNOsiZCiM0ztkmpTVEp7LGt3FxKWgS0a8//bHXbkVGED2hya+EKALTTUygvfQYgbjLrMy5xGqnyck32FKkKCbVTI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
