travis:
  secure:
    BINSTAR_TOKEN: fiYPupQxGCjnTcajvPGMElsOv8p1Ke/gbovkUPC6XVVrdJuZhTcefVfqEBnzBzb7L9doQ9rkXCNWOZaOKdV1qo5h+hqxr804fPydCSUDnGNpSoEsOfXTwZnal7xgenJAvqnPk0CWP91HqJQVnDkCJoaRZo0+RxdBddPJHFoVQpLKtuOWT3KrQsv4NMu2JGXmG9J05fjYXLgIAFblv7x8ddIAqLhivFa/f2OIxH3y76+emQVIx6qSqVeBGwMT7OFMVBSmvk5CE2JhaLriFwxbRc7/FIF34QPtRB4paoVOx3KYE3aL2evAB+6yX3cMx8sSrkpO0dsGs/B5BRgYyS/tHvQzjl4hV8Y8soLrxKAcENes+10duBDWACohcZYg4d7gFvva73xqGDgrz5z5a7LJBFfOOesMx9/XNiEq8rLZnfzkFtTEmYryC2DjkW7jdCm+44d8Uhr/Yn7DLeZomnaFc4sEr6XfCXzeg56EWTzwzL4sLhUFJyGKrBlxm/on0I7sxoDvSRSOZt3z0T7x3HMzDMVgpTlPItgbr0IDEtxJL9qEX+pdhOS9EvIHlZTUGarClFj1Y/8jdBrD+ZruVbYkNOsiZCiM0ztkmpTVEp7LGt3FxKWgS0a8//bHXbkVGED2hya+EKALTTUygvfQYgbjLrMy5xGqnyck32FKkKCbVTI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
